# Generated by Django 2.0.2 on 2018-02-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_delivery', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='service',
            field=models.ForeignKey(blank=True, help_text='برای اعمال تخفیف به یک نوع سرویس، نوع آن را مشخص کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_delivery.ServiceDetail', verbose_name='نوع خدمت'),
        ),
    ]
