# Generated by Django 2.0.2 on 2018-04-02 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_discountcoupon_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name_plural': 'کوپن\u200cهای تخفیف استفاده شده',
                'ordering': ('-created',),
                'verbose_name': 'کوپن تخفیف استفاده شده',
            },
        ),
        migrations.RemoveField(
            model_name='discountcoupon',
            name='max_amount',
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='max_discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='min_invoice_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل مبلغ فاکتور'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='single_user',
            field=models.BooleanField(default=False, verbose_name='تک کاربر'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='percent',
            field=models.PositiveIntegerField(blank=True, help_text='تخفیف درصدی در صورتی اعمال می\u200cشود که مبلغ را مشخص نکنید.', null=True, verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='ref_num',
            field=models.CharField(blank=True, help_text='کد در نظر گرفته شده برای تخفیف را وارد نمایید', max_length=20, null=True, unique=True, verbose_name='شماره مرجع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('model', 'DryCleaning'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'CarpetCleaning'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'AC'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Medical'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'HomeAppliance'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Plumbing'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Electricity'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Tuition'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Truck'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Cleaning'), ('app_label', 'service_delivery'), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره پیگیری'),
        ),
        migrations.AddField(
            model_name='useddiscounts',
            name='discount_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.DiscountCoupon', verbose_name='کوپن تخفیف'),
        ),
    ]
