# Generated by Django 2.0.2 on 2018-04-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='window_install',
        ),
        migrations.RemoveField(
            model_name='acitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='acitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='carpetcleaningitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carpetcleaningitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='drycleaning',
            name='manteau',
        ),
        migrations.RemoveField(
            model_name='drycleaning',
            name='shirt',
        ),
        migrations.RemoveField(
            model_name='drycleaning',
            name='suit',
        ),
        migrations.RemoveField(
            model_name='medicalsession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalsession',
            name='status',
        ),
        migrations.AddField(
            model_name='acitem',
            name='brand',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سامسونگ'), (2, 'ال\u200cجی'), (3, 'بوش'), (4, 'جنرال'), (5, 'پاناسونیک'), (6, 'گری'), (7, 'میدیا'), (8, 'هایس'), (9, 'توشیبا'), (10, 'تراست'), (11, 'میتوشی'), (12, 'هیتاچی'), (13, 'سایر')], null=True, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='acitem',
            name='engine',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1200), (2, 1800), (3, 2400), (4, 3000), (5, 3600), (6, 4200), (7, 4800), (8, 6000), (9, 9000)], null=True, verbose_name='موتور'),
        ),
        migrations.AddField(
            model_name='acitem',
            name='problem',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دستگاه روشن نمی\u200cشود'), (2, 'خوب سرد نمی\u200cکند'), (3, 'روی موتور نمی\u200cرود'), (4, 'لرزش غیر\u200cعادی'), (5, 'کولر یخ می\u200cزند'), (6, 'هنگام روشن شدن فیوز می\u200cپراند'), (7, 'ریموت کار نمی\u200cکند'), (8, 'بدنه کولر برق دارد'), (9, 'متناوباً خاموش و روشن می\u200cشود'), (10, 'سایر')], null=True, verbose_name='علائم خرابی'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'بندرعباس'), (2, 'کرمان'), (3, 'یزد')], default=1, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='city',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'بندرعباس'), (2, 'کرمان'), (3, 'یزد')], default=1, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='carpetcleaningitem',
            name='carpet_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'پلی\u200cاتیلن'), (2, 'ابریشم'), (3, 'سایر')], null=True, verbose_name='نوع فرش'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='female_worker_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد نیروی زن'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='male_worker_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد نیروی مرد'),
        ),
        migrations.AddField(
            model_name='drycleaning',
            name='clothes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='البسه'),
        ),
        migrations.AddField(
            model_name='homeappliance',
            name='problem',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دستگاه روشن نمی\u200cشود'), (2, 'صدای غیرعادی'), (3, 'کلیدها کار نمی\u200cکنند'), (4, 'سایر')], null=True, verbose_name='علائم خرابی'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='city',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'بندرعباس'), (2, 'کرمان'), (3, 'یزد')], default=1, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ابتدایی'), (2, 'متوسطه دوم (علوم تجربی)'), (3, 'متوسطه دوم (ریاضی فیزیک)'), (4, 'متوسطه'), (5, 'تیزهوشان')], null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_city',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'بندرعباس'), (2, 'کرمان'), (3, 'یزد')], default=1, null=True, verbose_name='شهر پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='carpetcleaningitem',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '۱ متر'), (2, '۳ متر'), (3, 'سایر')], null=True, verbose_name='اندازه'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='brand',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سامسونگ'), (2, 'ال\u200cجی'), (3, 'بوش'), (4, 'امرسان'), (5, 'اسنوا'), (6, 'سینجر'), (7, 'میدیا'), (8, 'دوو')], null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='home_appliance_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'یخچال'), (2, 'فریزر'), (3, 'ساید بای ساید'), (4, 'تلویزیون'), (5, 'جاروبرقی'), (6, 'ماشین لباس\u200cشویی'), (7, 'ماشین ظرف\u200cشویی'), (8, 'اجاق\u200cگاز'), (9, 'اجاق مایکرویو'), (10, 'هود')], null=True, verbose_name='نوع لوازم خانگی'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='service_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'نصب و راه\u200cاندازی'), (2, 'تعمیر'), (3, 'سرویس ساید بای ساید')], null=True, verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سال اول'), (2, 'سال دوم'), (3, 'سال سوم'), (4, 'سال چهارم'), (5, 'سال پنجم'), (6, 'سال ششم')], null=True, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='lesson_name',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ریاضی'), (2, 'فیزیک'), (3, 'شیمی'), (4, 'محاسبات'), (5, 'زیست\u200cشناسی'), (6, 'زمین\u200cشناسی'), (7, 'زبان انگلیسی'), (8, 'عربی'), (9, 'ادبیات')], null=True, verbose_name='اسم درس'),
        ),
    ]
