# Generated by Django 2.0.2 on 2018-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0002_auto_20180402_2301'),
    ]

    operations =[
        migrations.AlterField(
            model_name='carpetcleaningitem',
            name='carpet_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ماشینی'), (2, 'دستبافت'), (3, 'ابریشم'), (4, 'موکت'), (5, 'قالیچه')], null=True, verbose_name='نوع فرش'),
        ),
        migrations.AlterField(
            model_name='carpetcleaningitem',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '۱ متری'), (2, '۲ متر'), (3, '۳ متری'), (4, '۶ متری'), (5, '۹ متری'), (6, '۱۲ متری')], null=True, verbose_name='اندازه'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='brand',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سامسونگ'), (2, 'ال\u200cجی'), (3, 'بوش'), (4, 'امرسان'), (5, 'اسنوا'), (6, 'سینجر'), (7, 'میدیا'), (8, 'دوو'), (9, 'لکو'), (10, 'پاناسونیک'), (11, 'جنرال الکتریک'), (12, 'الکترواستیل'), (13, 'AEG'), (14, 'کنوود'), (15, 'هارداستون'), (16, 'فیلور'), (17, 'هایر'), (18, 'هیمالیا'), (19, 'بیمکث'), (20, 'استیل البرز'), (21, 'اخوان'), (22, 'داتیس'), (23, 'پیلوت'), (24, 'پارس خزر'), (25, 'هیتاچی'), (26, 'فیلیپس'), (27, 'زیمنس'), (28, 'آبسال'), (29, 'سونی'), (30, 'سایر')], null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='problem',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دستگاه روشن نمی\u200cشود'), (2, 'صدای غیرعادی'), (3, 'کلیدها کار نمی\u200cکنند'), (4, 'یخچال خنک نمی\u200cکند'), (5, 'برفک می\u200cزند'), (6, 'موتور خاموش و روشن می\u200cشود'), (7, 'بدنه دستگاه برق دارد'), (8, 'درب باز یا بسته نمی\u200cشود'), (9, 'یخ\u200cساز کار نمی\u200cکند'), (10, 'فریزر منجمد نمی\u200cکند'), (11, 'مکش هود ضعیف است'), (12, 'سنسور بو یا دما کار نمی\u200cکند'), (13, 'لرزش غیرعادی دارد'), (14, 'بعضی یا همه شعله\u200cها روشن نمی\u200cشود'), (15, 'فندک اجاق\u200cگاز کار نمی\u200cکند'), (16, 'ترموکوپل اجاف\u200cگاز کار نمی\u200cکند'), (17, 'ترموکوپل اجاف\u200cگاز کار نمی\u200cکند'), (18, 'دستگاه مکش قوی ندارد'), (19, 'کارکردن با بو یا دود سوختگی همراه است'), (20, 'روشن می\u200cشود اما کار نمی\u200cکند'), (21, 'اثر مواد شوینده روی لباس می\u200cماند'), (22, 'عدم تخلیه آب'), (23, 'خشک\u200cکن کار نمی\u200cکند'), (24, 'آب گرم نمی\u200cکند'), (25, 'درب آب می\u200cدهد'), (26, 'اتومات دستگاه کار نمی\u200cکند'), (27, 'ظرف\u200cها خوب شسته نمی\u200cشوند'), (28, 'سایر')], null=True, verbose_name='علائم خرابی'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='active_days',
            field=models.TextField(blank=True, help_text='این خدمت در چه روزهایی از هفته فعال است؟ برای انتخاب همه روزهای هفته می\u200cتوانید هیچکدام را انتخاب نکنید.', null=True, verbose_name='رورهای فعال'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='تعرفه'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سال اول'), (2, 'سال دوم'), (3, 'سال سوم'), (4, 'سال چهارم'), (5, 'سال پنجم'), (6, 'سال ششم'), (7, 'سال هفتم'), (8, 'سال هشتم'), (9, 'سال نهم'), (10, 'سال دهم'), (11, 'سال یازدهم'), (12, 'سال دوازدهم'), (13, 'ششم به هفتم'), (14, 'نهم به دهم')], null=True, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='lesson_name',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ریاضی'), (2, 'علوم تجربی'), (3, 'فارسی'), (4, 'نگارش'), (5, 'عربی'), (6, 'زبان انگلیسی'), (7, 'زیست\u200cشناسی'), (8, 'فیزیک'), (9, 'شیمی'), (10, 'محاسبان'), (11, 'هندسه'), (12, 'آمار و احتمالات'), (13, 'ریاضات گسسته'), (14, 'استعداد تحصیلی'), (15, 'زمین\u200cشناسی'), (16, 'ادبیات')], null=True, verbose_name='اسم درس'),
        ),
    ]
