# Generated by Django 2.0.2 on 2018-05-03 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0011_auto_20180503_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_invite_code',
            field=models.BooleanField(default=False, verbose_name='از کد دعوت کاربر دیگر استفاده کرده\u200cاست'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='content_type',
            field=models.OneToOneField(blank=True, limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'DryCleaning'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'CarpetCleaning'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'AC'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Medical'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Towing'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'HomeAppliance'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Plumbing'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Electricity'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Tuition'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Truck'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Cleaning'), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
