# Generated by Django 2.0.2 on 2018-05-04 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0014_auto_20180503_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='last_modified_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_moderator', to=settings.AUTH_USER_MODEL, verbose_name='ناظر آخرین تغییر'),
        ),
    ]
