# Generated by Django 2.0.2 on 2018-05-05 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0015_baseservice_last_modified_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
        migrations.AddField(
            model_name='baseservice',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitations_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد دعوت\u200cها'),
        ),
        migrations.AlterField(
            model_name='acitem',
            name='engine',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 12000), (2, 18000), (3, 24000), (4, 30000), (5, 36000), (6, 42000), (7, 48000), (8, 60000), (9, 90000)], null=True, verbose_name='موتور'),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'در حال بررسی'), (2, 'در حال انجام'), (3, 'خاتمه یافته'), (4, 'لفو شده توسط مشتری'), (5, 'لفو شده توسط سرویس\u200cدهنده')], default=1, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='home_appliance_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'یخچال'), (2, 'جاروبرقی'), (3, 'ماشین لباس\u200cشویی'), (4, 'ماشین ظرف\u200cشویی'), (5, 'اجاق\u200cگاز'), (6, 'هود')], null=True, verbose_name='نوع لوازم خانگی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'خشک\u200cشویی'), (2, 'قالی\u200cشویی'), (3, 'کولر گازی'), (4, 'پزشکی'), (5, 'امداد خودرو - نیسان یدک\u200cکش'), (6, 'امداد خودرو - جرثقیل'), (7, 'لوازم خانگی'), (8, 'لوله\u200cکشی'), (9, 'برق\u200cکاری'), (10, 'تدریس'), (11, 'نظافت')], null=True, verbose_name='نوع پرسنل'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='active_days',
            field=models.TextField(blank=True, help_text='این خدمت در چه روزهایی از هفته فعال است؟ برای انتخاب همه روزهای هفته می\u200cتوانید هیچکدام را انتخاب نکنید.', null=True, verbose_name='روزهای فعال'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='content_type',
            field=models.OneToOneField(blank=True, limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('model', 'DryCleaning'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'CarpetCleaning'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'AC'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Medical'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Towing'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'HomeAppliance'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Plumbing'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Electricity'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Tuition'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Truck'), ('app_label', 'service_delivery'), _connector='AND'), django.db.models.query_utils.Q(('model', 'Cleaning'), ('app_label', 'service_delivery'), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='lesson_name',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ریاضی'), (2, 'علوم تجربی'), (3, 'فارسی'), (4, 'نگارش'), (5, 'عربی'), (6, 'زبان انگلیسی'), (7, 'زیست\u200cشناسی'), (8, 'فیزیک'), (9, 'شیمی'), (10, 'حسابان'), (11, 'هندسه'), (12, 'آمار و احتمالات'), (13, 'ریاضات گسسته'), (14, 'استعداد تحصیلی'), (15, 'زمین\u200cشناسی'), (16, 'ادبیات')], null=True, verbose_name='اسم درس'),
        ),
    ]
