# Generated by Django 2.0.2 on 2018-05-11 10:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0018_auto_20180505_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='created_time',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='زمان ثبت سفارش'),
        ),
    ]
