# Generated by Django 2.0.2 on 2018-05-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0020_linkrequestednumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towing',
            fields=[
                ('baseservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_delivery.BaseService')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'امداد خودرو',
                'verbose_name_plural': 'امداد خودروها',
            },
            bases=('service_delivery.baseservice',),
        ),
    ]
