# Generated by Django 2.0.2 on 2018-05-21 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0022_auto_20180521_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappliance',
            name='problem',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دستگاه روشن نمی شود'), (2, 'یخچال خنک نمی کند'), (3, 'برفک می زند'), (4, 'صدای غیر عادی می دهد'), (5, 'موتور خاموش و روشن می شود'), (6, 'بدنه دستگاه برق دارد'), (7, 'درب بسته نمی شود'), (8, 'یخ ساز کار نمی کند'), (9, 'فریزر منجمد نمی کند'), (10, 'کلیدها کار نمی کند'), (11, 'مکش هود ضعیف است'), (12, 'سنسور بو یا دما کار نمی کند'), (13, 'هود لرزش غیرعادی دارد'), (14, 'هود صدای غیرعادی دارد'), (15, 'بعضی یا همه شعله ها روشن نمی شود'), (16, 'فندک اجاق گاز کار نمی کند'), (17, 'ترموکوپل اجاق گاز کار نمی کند'), (18, 'دستگاه مکش قوی ندارد'), (19, 'کارکردن با بو یا دود سوختگی'), (20, 'روشن می شود اما کار نمی کند'), (21, 'درب بسته نمی شود'), (22, 'اثر مواد شوینده روی لباس می  ماند'), (23, 'عدم تخلیه آب'), (24, 'دستگاه هنگام کار بوی سوختگی می دهد'), (25, 'لرزش غیرعادی دارد'), (26, 'درب باز یا بسته نمی شود'), (27, 'خشک کن کار نمی کند'), (28, 'آب گرم نمی کند'), (29, 'درب آب می دهد'), (30, 'کلیدها کار نمی کند'), (31, 'اتومات دستگاه کار نمی کند'), (32, 'ظرف ها خوب شسته نمی شوند'), (33, 'عدم تخلیه آب'), (34, 'سایر')], null=True, verbose_name='علائم خرابی'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='content_type',
            field=models.OneToOneField(blank=True, limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'DryCleaning'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'CarpetCleaning'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'AC'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Medical'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Towing'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'HomeAppliance'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Plumbing'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Electricity'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Tuition'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Truck'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'service_delivery'), ('model', 'Cleaning'), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
