# Generated by Django 2.0.2 on 2018-06-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_delivery', '0026_auto_20180602_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
    ]
