# Generated by Django 2.0.2 on 2018-02-26 13:56

from django.db import migrations, models
import drfpasswordless.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('to_alias', models.CharField(blank=True, max_length=40)),
                ('to_alias_type', models.CharField(blank=True, max_length=20)),
                ('key', models.CharField(default=drfpasswordless.models.generate_numeric_token, max_length=6, unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'created_at',
                'verbose_name': 'Callback Token',
                'abstract': False,
            },
        ),
    ]
